### ISSUE TITLE
Pretrained Model

### ISSUE THREAD

**Issue by OtiTantaoui** [xiaoyufenfei/ESNet#3]
Hello thanks for this repository. 
Can you also upload weight file for the model that you trained please as it will allow to save time and reduce cloud conception for testing purpose only. 
Thanks a lot.

**Comment by monghimng** [comment]
+1 The author also made LEDNet and did not release pretrained model. Not very good for public research :(

**Comment by xiaoyufenfei** [comment]
I will upload the code soon, thank you for your attention.
